#pragma once
int UNITS[(UINT)((int)MECHS::END + (int)ALIENS::END)]
{
	(int)MECHS::electrice,
	(int)MECHS::flame,
	(int)MECHS::guard,
	(int)MECHS::judo,
	(int)MECHS::laser,
	(int)MECHS::leap,
	(int)MECHS::punch,

	(int)MECHS::charge,
	(int)MECHS::jet,
	(int)MECHS::mirror,
	(int)MECHS::tank,
	(int)MECHS::unstable,
	(int)MECHS::wall,

	(int)MECHS::artillery,
	(int)MECHS::dstrike,
	(int)MECHS::ice,
	(int)MECHS::ignite,
	(int)MECHS::rockart,
	(int)MECHS::rocket,

	(int)MECHS::grav,
	(int)MECHS::nano,
	(int)MECHS::pulse,
	(int)MECHS::science,
	(int)MECHS::tele,

	(int)ALIENS::Beetle + (int)MECHS::tele + 1,
	(int)ALIENS::Blobber + (int)MECHS::tele + 1,
	(int)ALIENS::Burrower + (int)MECHS::tele + 1,
	(int)ALIENS::Centipede + (int)MECHS::tele + 1,
	(int)ALIENS::Crab + (int)MECHS::tele + 1,
	(int)ALIENS::Digger + (int)MECHS::tele + 1,
	(int)ALIENS::Firefly + (int)MECHS::tele + 1,
	(int)ALIENS::Hornet + (int)MECHS::tele + 1,
	(int)ALIENS::Jelly + (int)MECHS::tele + 1,
	(int)ALIENS::Leaper + (int)MECHS::tele + 1,
	(int)ALIENS::Scarab + (int)MECHS::tele + 1,
	(int)ALIENS::Scorpion + (int)MECHS::tele + 1,
	(int)ALIENS::Slime + (int)MECHS::tele + 1,
	(int)ALIENS::Spider + (int)MECHS::tele + 1,
};
int UNITS_WEAPONS[(UINT)((int)MECHS::END + (int)ALIENS::END)]{
	(int)WEAPON_T::NONE,//electrice,
	(int)WEAPON_T::NONE,//flame,
	(int)WEAPON_T::NONE,//guard,
	(int)WEAPON_T::NONE,//judo,
	(int)WEAPON_T::NONE,//laser,
	(int)WEAPON_T::NONE,//leap,
	(int)WEAPON_T::titan_fist,//punch,

	(int)WEAPON_T::NONE,//charge,
	(int)WEAPON_T::NONE,//jet,
	(int)WEAPON_T::NONE,//mirror,
	(int)WEAPON_T::taurus_cannon,//tank,
	(int)WEAPON_T::NONE,//unstable,
	(int)WEAPON_T::NONE,//wall,

	(int)WEAPON_T::artemis_artillery,//artillery,
	(int)WEAPON_T::NONE,//dstrike,
	(int)WEAPON_T::NONE,//ice,
	(int)WEAPON_T::NONE,//ignite,
	(int)WEAPON_T::NONE,//rockart,
	(int)WEAPON_T::NONE,//rocket,

	(int)WEAPON_T::NONE,//grav,
	(int)WEAPON_T::NONE,//nano,
	(int)WEAPON_T::NONE,//pulse,
	(int)WEAPON_T::NONE,//science,
	(int)WEAPON_T::NONE,//tele,

	(int)WEAPON_T::NONE,//Beetle,
	(int)WEAPON_T::NONE,//Blobber,
	(int)WEAPON_T::NONE,//Burrower,
	(int)WEAPON_T::NONE,//Centipede,
	(int)WEAPON_T::NONE,//Crab,
	(int)WEAPON_T::NONE,//Digger,
	(int)WEAPON_T::accelerating_thorax,//Firefly,
	(int)WEAPON_T::stinger,//Hornet,
	(int)WEAPON_T::NONE,//Jelly,
	(int)WEAPON_T::fangs,//Leaper,
	(int)WEAPON_T::NONE,//Scarab,
	(int)WEAPON_T::stinging,//Scorpion,
	(int)WEAPON_T::NONE,//Slime,
	(int)WEAPON_T::NONE,//Spider,
};
int GET_ALIEN_UNIT(int unitValue){return unitValue - (int)MECHS::tele + 1;}